# Generated by Django 4.1.1 on 2022-09-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
